import { HistoryModule } from "../models/HistoryModule.js";
import { PatientScript } from "../models/PatientScript.js";
import { SmartChecklist } from "../models/SmartChecklist.js";

const sourceReference = "Respiratory OSCE Stations PDF";

export async function seedRespiratoryPdfHistoryStations({ respiratory, breathlessnessGuide }) {
  const seeded = [];
  for (const station of respiratoryHistoryStations) {
    const patientScript = await PatientScript.findOneAndUpdate(
      { slug: station.patientScript.slug },
      { $set: station.patientScript },
      { upsert: true, new: true },
    );
    const checklist = await SmartChecklist.findOneAndUpdate(
      { slug: station.checklist.slug },
      { $set: station.checklist },
      { upsert: true, new: true },
    );
    const module = await HistoryModule.findOneAndUpdate(
      { slug: station.module.slug },
      {
        $set: {
          ...station.module,
          specialtyId: respiratory._id,
          historyGuideId: breathlessnessGuide._id,
          patientScriptId: patientScript._id,
          smartChecklistId: checklist._id,
        },
      },
      { upsert: true, new: true },
    );
    seeded.push(module);
  }
  return seeded;
}

const respiratoryHistoryStations = [
  {
    module: {
      title: "Suspected Adult Asthma",
      slug: "pdf-focused-history-diagnostic-planning-suspected-adult-asthma",
      presentingComplaint: "Episodic wheeze and chest tightness",
      systemOrTopic: "Asthma",
      stationType: "history",
      taskTags: ["history", "respiratory", "diagnostic-planning"],
      difficulty: "intermediate",
      timeLimitSeconds: 360,
      shortDescription: "Maya Khan, a 28-year-old primary-school teacher, reports episodic wheeze and chest tightness.",
      candidateInstructions: {
        context: "You are a medical officer in a respiratory outpatient clinic.",
        patientSummary: "Maya Khan, a 28-year-old primary-school teacher, reports episodic wheeze and chest tightness.",
        tasks: [
          "Take a focused respiratory history.",
          "Assess symptom pattern, triggers, control, risk factors, and red flags.",
          "Explain the likely diagnosis and the need for objective confirmation.",
          "Outline safe next steps.",
        ],
        examinationRequired: false,
        additionalInstructions: ["You have 8 minutes."],
      },
      examinerInstructions: "Do not prompt unless the candidate is completely stuck. Mark only observed behaviour. No examination is required.\nStation focus: Recognition of variable asthma-type symptoms, assessment of control and attack risk, and understanding that history alone does not confirm asthma.",
      keyAnswerGuide: "The history is compatible with asthma because symptoms are episodic, variable, nocturnal, trigger-related, and associated with atopy. Asthma should not be declared confirmed from symptoms alone. Appropriate objective evidence may include spirometry with bronchodilator testing, FeNO or blood eosinophils where recommended, serial peak-flow variability, or bronchial challenge/specialist assessment if uncertainty persists. A low FEV1/FVC indicates obstruction but is not specific to asthma, and FeNO supports type-2 airway inflammation but is not independently diagnostic.\nIf treatment must begin before confirmation, use an ICS-containing approach according to local protocol, not routine long-term short-acting bronchodilator-only care. Review inhaler technique, adherence, vaping, rhinitis, triggers, and occupational factors. Provide a written action plan and follow-up. Urgent help is required for rapidly worsening breathlessness, inability to speak normally, blue lips, exhaustion, faintness, or poor response to prescribed reliever treatment.",
      suggestedCandidateApproach: [
        "Introduce yourself, confirm identity, gain consent, and check current distress.",
        "Characterise the four core symptoms, variability, timing, triggers, and relief.",
        "Assess frequency, night waking, activity limitation, reliever use, and deterioration.",
        "Ask about previous severe attacks, atopy, exposures, medicines, and alternatives.",
        "Explore the patient's ideas, concerns, and expectations.",
        "Summarise, explain diagnostic uncertainty, propose objective tests, and safety-net.",
      ],
      learningNotes: "Your pattern suggests asthma because the symptoms vary, are worse at night, and occur with triggers and allergies. However, symptoms alone cannot prove asthma. We should arrange objective breathing and inflammation tests. If treatment is needed now, it should include an inhaled corticosteroid according to our local pathway. Asthma is usually controllable, and we will also give you an action plan. Seek urgent help if you cannot speak normally, become blue or exhausted, or your prescribed reliever does not help.",
      commonMistakes: [],
      keyDifferentials: [],
      vivaQuestions: [
        { question: "Can you tell from my symptoms that I definitely have asthma?", modelAnswerOutline: "" },
        { question: "Will I need a breathing test?", modelAnswerOutline: "" },
        { question: "Can asthma be controlled?", modelAnswerOutline: "" },
      ],
      sourceReferences: [sourceReference],
      status: "published",
      version: 1,
      createdBy: "seed",
      reviewedBy: "seed",
      publishedAt: new Date(),
    },
    patientScript: patientScript({
      name: "Maya Khan - Suspected Adult Asthma",
      slug: "pdf-maya-khan-suspected-adult-asthma",
      patientIdentity: { name: "Maya Khan", age: 28, sex: "", occupation: "primary-school teacher", pronouns: "" },
      baselineState: { generalAppearance: "comfortable at rest", currentDistress: "", communicationAbility: "" },
      openingStatement: "For the past few months, I've had times when my chest feels tight and I start wheezing.",
      demeanor: { general: "Cooperative and mildly anxious.", verbosity: "Do not volunteer triggers, atopy, vaping, or previous severity unless asked." },
      facts: [
        fact("adult_asthma_duration", "HPC", "duration", "Duration", "About four months.", ["duration", "how long", "onset"]),
        fact("adult_asthma_pattern", "HPC", "pattern", "Pattern", "It comes and goes three or four times a week. I feel normal between episodes.", ["pattern", "frequency", "come and go"]),
        fact("adult_asthma_timing", "HPC", "timing", "Timing", "It is often worse at night or early in the morning.", ["timing", "night", "morning"]),
        fact("adult_asthma_symptoms", "HPC", "symptoms", "Symptoms", "Wheeze, chest tightness, dry cough, and breathlessness occur together.", ["symptoms", "wheeze", "chest tightness", "cough", "breathlessness"]),
        fact("adult_asthma_triggers", "HPC", "triggers", "Triggers", "Exercise, cold air, cats, classroom dust, and spring pollen.", ["triggers", "exercise", "cold air", "cats", "dust", "pollen"]),
        fact("adult_asthma_relief", "HPC", "relief", "Relief", "A relative's blue inhaler helped briefly on two occasions.", ["relief", "inhaler", "helps"]),
        fact("adult_asthma_impact", "ICE", "impact", "Impact", "Occasionally stops exercise and interrupts sleep; no time off work.", ["impact", "exercise", "sleep", "work"]),
        fact("adult_asthma_current_danger", "RED_FLAG", "current_danger_symptoms", "Current danger symptoms", "No severe breathlessness, blue lips, fainting, or inability to speak.", ["danger", "blue lips", "fainting", "speak"]),
        fact("adult_asthma_previous_severity", "HPC", "previous_severity", "Previous severity", "No emergency attendance, admission, intensive care, or intubation.", ["emergency", "admission", "intensive care", "intubation"]),
        fact("adult_asthma_atopy", "PMH", "atopy", "Atopy", "Childhood eczema and seasonal allergic rhinitis.", ["eczema", "allergic rhinitis", "atopy"]),
        fact("adult_asthma_family_history", "FH", "family_history", "Family history", "Mother has asthma.", ["family", "mother", "asthma"]),
        fact("adult_asthma_smoking_exposure", "SH", "smoking_exposure", "Smoking/exposure", "Does not smoke cigarettes; vapes socially. No chemical exposure at work.", ["smoke", "vape", "chemical exposure"]),
        fact("adult_asthma_medication", "DH", "medication", "Medication", "No regular medicines; no beta-blocker or NSAID-associated symptoms.", ["medicine", "medication", "beta-blocker", "NSAID"]),
        fact("adult_asthma_alternatives_red_flags", "RED_FLAG", "alternatives_red_flags", "Alternatives/red flags", "No fever, weight loss, coughing blood, leg swelling, or persistent daily symptoms.", ["fever", "weight loss", "coughing blood", "leg swelling"]),
      ],
      emotionalCues: [{ cueId: "adult_asthma_exercise_worry", condition: "If the candidate is empathetic", response: "Thank you. I was worried you might tell me to stop all exercise." }],
      patientQuestions: ["Can you tell from my symptoms that I definitely have asthma?", "Will I need a breathing test?", "Can asthma be controlled?"],
      expectedPatientAttitude: "Cooperative and mildly anxious. Do not volunteer triggers, atopy, vaping, or previous severity unless asked.",
    }),
    checklist: checklist({
      title: "Focused history and diagnostic planning for suspected adult asthma checklist",
      slug: "pdf-adult-asthma-history-checklist",
      items: [
        row("adult_asthma_rapport_safety", "Rapport, consent, and immediate safety", "Introduces self; confirms identity; gains consent; checks current distress", ["introduce_self", "consent", "current_distress"], [], "major"),
        row("adult_asthma_core_symptoms", "Core symptom history", "Wheeze, breathlessness, cough, chest tightness, onset, duration, variability", ["symptoms", "duration", "variability"], ["adult_asthma_symptoms", "adult_asthma_duration", "adult_asthma_pattern"], "major"),
        row("adult_asthma_pattern_triggers", "Pattern and triggers", "Night/early morning, exercise, seasonal, allergen, cold-air, occupational pattern", ["timing", "triggers"], ["adult_asthma_timing", "adult_asthma_triggers"], "major"),
        row("adult_asthma_control_impact", "Control and impact", "Frequency, night waking, activity limitation, reliever use, deterioration", ["pattern", "impact", "relief"], ["adult_asthma_pattern", "adult_asthma_impact", "adult_asthma_relief"], "major"),
        row("adult_asthma_previous_severity", "Previous severity", "Emergency visits, admission, ICU, intubation, systemic steroid courses", ["previous_severity"], ["adult_asthma_previous_severity"], "critical"),
        row("adult_asthma_background_risks", "Background risks", "Atopy, rhinitis, family history, smoking/vaping, medicines, work/home exposures", ["atopy", "family_history", "smoking_exposure", "medication"], ["adult_asthma_atopy", "adult_asthma_family_history", "adult_asthma_smoking_exposure", "adult_asthma_medication"], "major"),
        row("adult_asthma_explanation_testing", "Explanation and testing", "Suspects asthma but explains need for objective confirmation", ["explanation", "testing"], [], "major"),
        row("adult_asthma_safe_counselling", "Safe counselling", "ICS-containing principle, written plan, follow-up, urgent warning symptoms", ["safe_counselling"], ["adult_asthma_current_danger"], "critical"),
      ],
    }),
  },
  {
    module: {
      title: "Suspected Pulmonary Embolism",
      slug: "pdf-focused-history-immediate-assessment-suspected-pulmonary-embolism",
      presentingComplaint: "Sudden breathlessness and pleuritic chest pain",
      systemOrTopic: "Pulmonary embolism",
      stationType: "history",
      taskTags: ["history", "respiratory", "acute-assessment"],
      difficulty: "advanced",
      timeLimitSeconds: 360,
      shortDescription: "Daniel Reed, aged 54, developed sudden breathlessness and pleuritic chest pain three weeks after knee replacement.",
      candidateInstructions: {
        context: "You are a medical officer in the acute assessment unit.",
        patientSummary: "Daniel Reed, aged 54, developed sudden breathlessness and pleuritic chest pain three weeks after knee replacement.",
        tasks: ["Take a focused history, assess immediate danger and thromboembolic risk, and present an investigation and escalation plan."],
        examinationRequired: false,
        additionalInstructions: ["You have 8 minutes."],
      },
      examinerInstructions: "Observe whether the candidate prioritises physiological stability and uses a validated pre-test-probability pathway. Do not reward indiscriminate D-dimer testing or a fixed anticoagulant choice without considering contraindications.",
      keyAnswerGuide: "PE is a leading possibility because of sudden pleuritic symptoms, recent surgery and immobility, and possible DVT. The first priority is stability. Hypotension, significant hypoxaemia, syncope, confusion, or rapid deterioration requires immediate senior/emergency escalation and an emergency PE pathway.\nIf stable, apply a validated clinical-probability approach. D-dimer is mainly used when probability is not high and the relevant pathway indicates it. High clinical probability generally proceeds to definitive imaging; a negative D-dimer should not be used to exclude PE in a high-probability case. CTPA is common, but alternative imaging may be required. Review renal function, contrast issues, pregnancy where relevant, bleeding risk, and anticoagulant considerations. Timing and choice of anticoagulation follow local protocol. Thrombolysis is not routine for biomarker elevation or right-heart strain alone; it is principally considered in haemodynamic instability or selected deterioration after specialist review.",
      suggestedCandidateApproach: [
        "Check distress, syncope, haemodynamic symptoms, and current chest pain.",
        "Characterise onset, pleuritic pain, breathlessness, hemoptysis, and collapse.",
        "Ask about DVT symptoms and previous venous thrombosis.",
        "Cover provoking factors, malignancy, hormones, pregnancy/postpartum state, and thrombophilia.",
        "Consider ACS, pneumothorax, pneumonia, and aortic disease.",
        "Review bleeding and imaging risks, then explain urgent probability-based assessment.",
      ],
      learningNotes: "A blood clot in the lung is an important possibility because your symptoms began suddenly after surgery and your calf is swollen. We must first check your oxygen level, blood pressure, heart tracing, and overall stability. We will then use a validated risk pathway to decide whether you need a blood test, imaging, and anticoagulation. If you become faint, confused, blue, or much more breathless, that requires immediate emergency escalation.",
      commonMistakes: [],
      keyDifferentials: [],
      vivaQuestions: [
        { question: "Could this be a clot?", modelAnswerOutline: "" },
        { question: "Am I in immediate danger?", modelAnswerOutline: "" },
        { question: "Will I need a scan?", modelAnswerOutline: "" },
      ],
      sourceReferences: [sourceReference],
      status: "published",
      version: 1,
      createdBy: "seed",
      reviewedBy: "seed",
      publishedAt: new Date(),
    },
    patientScript: patientScript({
      name: "Daniel Reed - Suspected Pulmonary Embolism",
      slug: "pdf-daniel-reed-suspected-pulmonary-embolism",
      patientIdentity: { name: "Daniel Reed", age: 54, sex: "", occupation: "", pronouns: "" },
      baselineState: { generalAppearance: "", currentDistress: "mildly breathless", communicationAbility: "can speak in full sentences" },
      openingStatement: "I suddenly became short of breath this morning, and it hurts when I breathe in.",
      demeanor: { general: "Anxious but cooperative.", verbosity: "Do not volunteer calf symptoms or surgery details until asked." },
      facts: [
        fact("pe_onset", "HPC", "onset", "Onset", "Sudden, two hours ago.", ["onset", "when", "sudden"]),
        fact("pe_pain", "HPC", "pain", "Pain", "Sharp, right-sided, worse with deep breathing.", ["pain", "pleuritic", "right-sided", "deep breathing"]),
        fact("pe_associated_symptoms", "HPC", "associated_symptoms", "Associated symptoms", "Brief light-headedness; no collapse or hemoptysis.", ["light-headed", "collapse", "hemoptysis"]),
        fact("pe_dvt_symptoms", "HPC", "dvt_symptoms", "DVT symptoms", "Left calf swollen and sore for two days.", ["calf", "leg", "swollen", "sore", "DVT"]),
        fact("pe_provocation", "HPC", "provocation", "Provocation", "Knee replacement three weeks ago and reduced mobility since.", ["surgery", "knee replacement", "mobility", "immobility"]),
        fact("pe_previous_risk", "PMH", "previous_risk", "Previous risk", "No previous DVT/PE, active cancer, long-haul travel, or known thrombophilia.", ["previous", "cancer", "travel", "thrombophilia"]),
        fact("pe_medication", "DH", "medication", "Medication", "Postoperative prophylaxis has finished; not currently anticoagulated.", ["prophylaxis", "anticoagulated", "medication"]),
        fact("pe_bleeding_risk", "PMH", "bleeding_risk", "Bleeding risk", "No major bleeding, ulcer, intracranial bleed, or bleeding disorder.", ["bleeding", "ulcer", "intracranial", "bleeding disorder"]),
        fact("pe_imaging_considerations", "OTHER", "imaging_considerations", "Imaging considerations", "No known kidney disease or contrast allergy.", ["kidney", "renal", "contrast", "allergy"]),
        fact("pe_alternatives", "RED_FLAG", "alternatives", "Alternatives", "No fever, productive cough, trauma, tearing back pain, or unilateral absent breath sounds.", ["fever", "productive cough", "trauma", "back pain", "breath sounds"]),
        fact("pe_current_instability", "RED_FLAG", "current_instability", "Current instability", "No ongoing faintness, confusion, blue lips, or worsening inability to speak.", ["faint", "confusion", "blue lips", "speak"]),
      ],
      emotionalCues: [{ cueId: "pe_reassured", condition: "If reassured appropriately", response: "I understand you need to assess me quickly rather than guess." }],
      patientQuestions: ["Could this be a clot?", "Am I in immediate danger?", "Will I need a scan?"],
      expectedPatientAttitude: "Anxious but cooperative. Do not volunteer calf symptoms or surgery details until asked.",
    }),
    checklist: checklist({
      title: "Focused history and immediate assessment planning for suspected pulmonary embolism checklist",
      slug: "pdf-pulmonary-embolism-history-checklist",
      items: [
        row("pe_immediate_safety", "Immediate safety", "Checks severe distress, syncope, hypotension, hypoxaemia, ongoing pain", ["current_instability", "immediate_safety"], ["pe_current_instability"], "critical"),
        row("pe_symptom_analysis", "Symptom analysis", "Sudden onset, dyspnoea, pleuritic pain, cough, hemoptysis, syncope", ["onset", "pain", "associated_symptoms"], ["pe_onset", "pe_pain", "pe_associated_symptoms"], "major"),
        row("pe_dvt_previous_vte", "DVT/previous VTE", "Unilateral calf pain/swelling and previous DVT/PE", ["dvt_symptoms", "previous_risk"], ["pe_dvt_symptoms", "pe_previous_risk"], "major"),
        row("pe_provoking_risks", "Provoking risks", "Surgery, trauma, immobility, travel, admission, lines", ["provocation"], ["pe_provocation"], "major"),
        row("pe_additional_risks", "Additional risks", "Cancer, pregnancy/postpartum state, oestrogen, thrombophilia", ["previous_risk"], ["pe_previous_risk"], "major"),
        row("pe_differentials", "Differentials", "ACS, pneumothorax, pneumonia, aortic pathology", ["alternatives"], ["pe_alternatives"], "major"),
        row("pe_treatment_imaging", "Treatment/imaging considerations", "Bleeding, anticoagulants, renal disease, allergy, comorbidity", ["bleeding_risk", "imaging_considerations", "medication"], ["pe_bleeding_risk", "pe_imaging_considerations", "pe_medication"], "major"),
        row("pe_plan_communication", "Plan and communication", "Urgency, observations, probability-based D-dimer/imaging, escalation", ["plan", "communication"], [], "critical"),
      ],
    }),
  },
  {
    module: {
      title: "Hemoptysis",
      slug: "pdf-focused-history-hemoptysis-malignancy-tuberculosis-risk",
      presentingComplaint: "Hemoptysis",
      systemOrTopic: "Hemoptysis",
      stationType: "history",
      taskTags: ["history", "respiratory", "urgent-investigation"],
      difficulty: "advanced",
      timeLimitSeconds: 360,
      shortDescription: "Peter Mensah, aged 61, has coughed up blood several times this week.",
      candidateInstructions: {
        context: "You are a medical officer in a rapid-access respiratory clinic.",
        patientSummary: "Peter Mensah, aged 61, has coughed up blood several times this week.",
        tasks: ["Take a focused history, assess immediate danger, and outline urgent investigations and safety-netting."],
        examinationRequired: false,
        additionalInstructions: ["You have 8 minutes."],
      },
      examinerInstructions: "The candidate should distinguish true hemoptysis from nasal, oral, and gastrointestinal bleeding; assess airway and physiological danger; and consider malignancy, TB, infection, bronchiectasis, and PE.",
      keyAnswerGuide: "This is true, currently non-life-threatening hemoptysis, but the persistent cough, weight loss, smoking, occupational history, and TB background require urgent investigation. Danger should not be defined by one rigid volume threshold; airway compromise, impaired gas exchange, haemodynamic effects, and bleeding rate are more important.\nInitial assessment includes observations and focused cardiorespiratory examination, FBC, coagulation profile, renal/liver tests, and group-and-save if bleeding is significant. Arrange chest radiography followed by urgent CT/chest-specialist assessment where indicated. Request sputum microbiology, including TB molecular testing and culture according to local protocol. If pulmonary TB is suspected, follow local respiratory precautions and public-health procedures. Brisk bleeding or breathing difficulty is an airway emergency requiring senior, anaesthetic, respiratory, and interventional support.",
      suggestedCandidateApproach: [
        "Confirm that the material truly comes from the lower respiratory tract.",
        "Establish amount, rate, frequency, clots, progression, and current danger.",
        "Ask about infection, recurrent sputum, weight loss, appetite, and night sweats.",
        "Cover smoking, occupational exposure, cancer history, TB risks, and immunosuppression.",
        "Ask about PE risk, bronchiectasis, anticoagulants, and bleeding disorders.",
        "Explain that several causes are possible, arrange urgent assessment, and safety-net.",
      ],
      learningNotes: "Coughing blood does not automatically mean cancer, but cancer is one important possibility, alongside infection, tuberculosis, bronchiectasis, and a blood clot. Because you also have a persistent cough and weight loss, you need urgent chest imaging and sputum tests. If the bleeding increases, you pass clots, become breathless, faint, confused, or blue, call emergency services immediately.",
      commonMistakes: [],
      keyDifferentials: [],
      vivaQuestions: [
        { question: "Does coughing blood mean I have lung cancer?", modelAnswerOutline: "" },
        { question: "Could I pass anything to my family?", modelAnswerOutline: "" },
        { question: "How urgently do I need tests?", modelAnswerOutline: "" },
      ],
      sourceReferences: [sourceReference],
      status: "published",
      version: 1,
      createdBy: "seed",
      reviewedBy: "seed",
      publishedAt: new Date(),
    },
    patientScript: patientScript({
      name: "Peter Mensah - Hemoptysis",
      slug: "pdf-peter-mensah-hemoptysis",
      patientIdentity: { name: "Peter Mensah", age: 61, sex: "", occupation: "former construction worker", pronouns: "" },
      baselineState: {},
      openingStatement: "I've coughed up blood a few times this week.",
      demeanor: { general: "Cooperative but guarded.", verbosity: "Provide constitutional and TB details only if specifically asked." },
      facts: [
        fact("hemoptysis_description", "HPC", "description", "Description", "Bright-red blood mixed with sputum, about a teaspoon on three occasions.", ["description", "amount", "blood", "sputum"]),
        fact("hemoptysis_source", "HPC", "source", "Source", "Occurs after coughing; no nosebleed, bleeding gums, vomiting, or coffee-ground material.", ["source", "nosebleed", "bleeding gums", "vomiting", "coffee-ground"]),
        fact("hemoptysis_immediate_impact", "RED_FLAG", "immediate_impact", "Immediate impact", "No large clots, current breathlessness, dizziness, syncope, or choking.", ["clots", "breathlessness", "dizziness", "syncope", "choking"]),
        fact("hemoptysis_respiratory_history", "HPC", "respiratory_history", "Respiratory history", "Six-week cough and reduced appetite.", ["cough", "appetite"]),
        fact("hemoptysis_constitutional", "ROS", "constitutional_symptoms", "Constitutional symptoms", "Four-kilogram unintentional weight loss and night sweats.", ["weight loss", "night sweats", "constitutional"]),
        fact("hemoptysis_smoking", "SH", "smoking", "Smoking", "Forty pack-years; still smokes.", ["smoking", "pack-years"]),
        fact("hemoptysis_occupation", "SH", "occupation", "Occupation", "Previous demolition work with inconsistent protection.", ["occupation", "demolition", "protection"]),
        fact("hemoptysis_tb_risk", "PMH", "tb_risk", "TB risk", "Born in a higher-incidence country; brother was treated for TB many years ago.", ["TB", "country", "brother", "contact"]),
        fact("hemoptysis_other_causes", "PMH", "other_causes", "Other causes", "No known bronchiectasis, recent PE risk, anticoagulant use, bleeding disorder, or heart disease.", ["bronchiectasis", "PE", "anticoagulant", "bleeding disorder", "heart disease"]),
        fact("hemoptysis_infection", "HPC", "infection", "Infection", "Occasional low fever; no sudden pleuritic pain.", ["infection", "fever", "pleuritic pain"]),
      ],
      emotionalCues: [{ cueId: "hemoptysis_cancer_concern", condition: "If asked about concerns", response: "I'm frightened this might be cancer." }],
      patientQuestions: ["Does coughing blood mean I have lung cancer?", "Could I pass anything to my family?", "How urgently do I need tests?"],
      expectedPatientAttitude: "Cooperative but guarded. Provide constitutional and TB details only if specifically asked.",
    }),
    checklist: checklist({
      title: "Focused history for hemoptysis with lung malignancy and tuberculosis risk checklist",
      slug: "pdf-hemoptysis-history-checklist",
      items: [
        row("hemoptysis_confirms_true", "Confirms true hemoptysis", "Excludes nasal, oral, and gastrointestinal sources", ["source"], ["hemoptysis_source"], "major"),
        row("hemoptysis_quantifies_safely", "Quantifies safely", "Amount, rate, frequency, duration, clots, progression; no rigid threshold", ["description"], ["hemoptysis_description"], "major"),
        row("hemoptysis_immediate_danger", "Immediate danger", "Airway symptoms, breathlessness, chest pain, dizziness, syncope", ["immediate_impact"], ["hemoptysis_immediate_impact"], "critical"),
        row("hemoptysis_infection_systemic", "Infection/systemic features", "Fever, sputum, recurrent infection, night sweats, weight/appetite change", ["infection", "constitutional_symptoms", "respiratory_history"], ["hemoptysis_infection", "hemoptysis_constitutional", "hemoptysis_respiratory_history"], "major"),
        row("hemoptysis_malignancy_risks", "Malignancy risks", "Smoking, occupation, previous cancer, persistent suspicious symptoms", ["smoking", "occupation"], ["hemoptysis_smoking", "hemoptysis_occupation"], "major"),
        row("hemoptysis_tb_risks", "TB risks", "Contact, country/residence, immunosuppression, previous TB", ["tb_risk"], ["hemoptysis_tb_risk"], "major"),
        row("hemoptysis_other_causes_medicines", "Other causes/medicines", "Anticoagulants, bleeding disorder, bronchiectasis, PE, cardiac disease", ["other_causes"], ["hemoptysis_other_causes"], "major"),
        row("hemoptysis_urgent_plan", "Urgent plan", "Imaging, microbiology, precautions if indicated, explicit emergency advice", ["urgent_plan"], [], "critical"),
      ],
    }),
  },
  {
    module: {
      title: "Suspected Interstitial Lung Disease",
      slug: "pdf-focused-occupational-environmental-history-suspected-interstitial-lung-disease",
      presentingComplaint: "Progressive exertional breathlessness and persistent dry cough",
      systemOrTopic: "Interstitial lung disease",
      stationType: "history",
      taskTags: ["history", "respiratory", "occupational-history"],
      difficulty: "advanced",
      timeLimitSeconds: 360,
      shortDescription: "Ahmed Saleh, aged 58, has progressive exertional breathlessness and a persistent dry cough.",
      candidateInstructions: {
        context: "You are a medical officer in a respiratory clinic.",
        patientSummary: "Ahmed Saleh, aged 58, has progressive exertional breathlessness and a persistent dry cough.",
        tasks: ["Take a focused history, concentrating on occupational and environmental exposure, and explain the next steps."],
        examinationRequired: false,
        additionalInstructions: ["You have 8 minutes."],
      },
      examinerInstructions: "Reward chronological, task-based exposure assessment rather than job titles alone. The candidate should consider latency, intensity, protection, alternative ILD causes, functional testing, imaging, and occupational-health input.",
      keyAnswerGuide: "Exposure-related ILD is possible, particularly with prolonged engineered-stone dust exposure. The candidate should not promise reversibility or a definite prognosis. Diagnosis requires oxygenation assessment, lung function including gas transfer, chest imaging and, when indicated, high-resolution CT and multidisciplinary specialist review. Tests for connective-tissue disease should be guided by the history.\nThe patient should reduce or stop harmful exposure while urgent occupational-health and respiratory advice is obtained, subject to local pathways. Workplace reporting and compensation arrangements are jurisdiction-specific. Address smoking, vaccination, rehabilitation, comorbidity, and oxygen only when a need is demonstrated.",
      suggestedCandidateApproach: [
        "Characterise progression, exercise tolerance, cough, and acute red flags.",
        "Obtain a lifetime job history with dates and specific tasks.",
        "Ask about dust type, intensity, visible exposure, ventilation, extraction, and PPE.",
        "Explore home, hobby, animal, mould, farming, and renovation exposures.",
        "Cover smoking, relevant drugs, radiotherapy, autoimmune symptoms, and family history.",
        "Summarise uncertainty, advise exposure reduction, and propose lung function, imaging, and specialist review.",
      ],
      learningNotes: "Your long history of cutting stone dust could be relevant to scarring or inflammation in the lungs, but we cannot confirm the cause or permanence from the history alone. We should assess oxygen levels at rest and on exercise, perform full lung-function tests, and arrange imaging. Until specialist and occupational-health review, reducing further dust exposure is important. Seek urgent help for sudden worsening, chest pain, coughing blood, confusion, or blue lips.",
      commonMistakes: [],
      keyDifferentials: [],
      vivaQuestions: [
        { question: "Has my job damaged my lungs permanently?", modelAnswerOutline: "" },
        { question: "Should I stop work now?", modelAnswerOutline: "" },
        { question: "Will I need a scan?", modelAnswerOutline: "" },
      ],
      sourceReferences: [sourceReference],
      status: "published",
      version: 1,
      createdBy: "seed",
      reviewedBy: "seed",
      publishedAt: new Date(),
    },
    patientScript: patientScript({
      name: "Ahmed Saleh - Suspected Interstitial Lung Disease",
      slug: "pdf-ahmed-saleh-suspected-interstitial-lung-disease",
      patientIdentity: { name: "Ahmed Saleh", age: 58, sex: "", occupation: "kitchen-worktop fabricator", pronouns: "" },
      baselineState: {},
      openingStatement: "I'm getting more out of breath when I walk, and I have a dry cough that won't go away.",
      demeanor: { general: "Initially frustrated, then cooperative.", verbosity: "Do not volunteer specific work tasks or control failures unless asked." },
      facts: [
        fact("ild_course", "HPC", "course", "Course", "Gradual progression over 18 months.", ["course", "progression", "how long"]),
        fact("ild_function", "HPC", "function", "Function", "Stops after one flight of stairs; no resting breathlessness.", ["function", "stairs", "resting breathlessness"]),
        fact("ild_cough", "HPC", "cough", "Cough", "Dry; no sputum or wheeze.", ["cough", "sputum", "wheeze"]),
        fact("ild_red_flags", "RED_FLAG", "red_flags", "Red flags", "No fever, acute chest pain, or hemoptysis.", ["fever", "chest pain", "hemoptysis"]),
        fact("ild_current_work", "SH", "current_work", "Current work", "Twenty years cutting engineered stone, often with visible dust.", ["work", "engineered stone", "dust"]),
        fact("ild_controls", "SH", "controls", "Controls", "Respiratory protection inconsistent; extraction equipment unreliable.", ["protection", "PPE", "extraction", "equipment"]),
        fact("ild_temporal_relation", "SH", "temporal_relation", "Temporal relation", "Not clearly better on weekends or holidays.", ["weekends", "holidays", "better"]),
        fact("ild_previous_work", "SH", "previous_work", "Previous work", "Demolition and insulation removal.", ["previous work", "demolition", "insulation"]),
        fact("ild_home_environment", "SH", "home_environment", "Home/environment", "No birds, mould, water damage, farming, or hot-tub exposure.", ["birds", "mould", "water damage", "farming", "hot-tub"]),
        fact("ild_other_causes", "PMH", "other_causes", "Other causes", "No relevant fibrogenic medicine, chest radiotherapy, inflammatory joint symptoms, rash, or family history of fibrotic lung disease.", ["medicine", "radiotherapy", "joint", "rash", "family"]),
        fact("ild_smoking", "SH", "smoking", "Smoking", "Ten pack-years; stopped five years ago.", ["smoking", "pack-years"]),
        fact("ild_impact", "ICE", "impact", "Impact", "Worried about continued employment and supporting family.", ["impact", "employment", "family"]),
      ],
      emotionalCues: [{ cueId: "ild_workplace_anger", condition: "If acknowledged", response: "I want to know what can be done and whether I should keep working there." }],
      patientQuestions: ["Has my job damaged my lungs permanently?", "Should I stop work now?", "Will I need a scan?"],
      expectedPatientAttitude: "Initially frustrated, then cooperative. Do not volunteer specific work tasks or control failures unless asked.",
    }),
    checklist: checklist({
      title: "Focused occupational and environmental history for suspected interstitial lung disease checklist",
      slug: "pdf-interstitial-lung-disease-occupational-history-checklist",
      items: [
        row("ild_symptom_course_impact", "Symptom course/impact", "Progression, exercise tolerance, cough, daily activities", ["course", "function", "cough", "impact"], ["ild_course", "ild_function", "ild_cough", "ild_impact"], "major"),
        row("ild_acute_red_flags", "Acute red flags", "Resting dyspnoea, hemoptysis, fever, chest pain, sudden change", ["red_flags"], ["ild_red_flags", "ild_function"], "critical"),
        row("ild_lifetime_job_history", "Lifetime job history", "Chronology and specific tasks, not titles alone", ["current_work", "previous_work"], ["ild_current_work", "ild_previous_work"], "major"),
        row("ild_inorganic_exposures", "Inorganic exposures", "Engineered stone, silica, asbestos, coal, metals, construction", ["current_work", "previous_work"], ["ild_current_work", "ild_previous_work"], "major"),
        row("ild_organic_environmental", "Organic/environmental exposures", "Birds, mould, farming, water damage, hobbies, renovation", ["home_environment"], ["ild_home_environment"], "major"),
        row("ild_exposure_control", "Exposure control", "Duration, intensity, PPE, extraction, co-worker illness, latency", ["controls", "temporal_relation"], ["ild_controls", "ild_temporal_relation"], "major"),
        row("ild_alternative_causes", "Alternative causes", "Smoking, drugs, radiotherapy, autoimmune symptoms, family history", ["smoking", "other_causes"], ["ild_smoking", "ild_other_causes"], "major"),
        row("ild_safe_plan", "Safe plan", "Oxygenation, lung function, HRCT where indicated, specialist/occupational review", ["safe_plan"], [], "critical"),
      ],
    }),
  },
];

function patientScript({ name, slug, patientIdentity, baselineState, openingStatement, demeanor, facts, emotionalCues, patientQuestions, expectedPatientAttitude }) {
  return {
    name,
    slug,
    patientIdentity,
    baselineState,
    openingStatement,
    demeanor,
    facts: [
      {
        factId: `${slug}_opening`,
        section: "PC",
        conceptId: "opening_statement",
        label: "Opening Statement",
        value: openingStatement,
        naturalResponse: openingStatement,
        revealPolicy: "OPENING",
        triggerConcepts: ["opening_statement"],
        synonyms: ["opening statement"],
        relatedChecklistItemIds: [],
      },
      ...facts,
    ],
    emotionalCues,
    patientQuestions: patientQuestions.map((question) => ({ trigger: "patient_question", question })),
    expectedPatientAttitude,
    unknownFactPolicy: "If a fact is not supplied in the station script, do not invent details.",
    sourceReferences: [sourceReference],
    status: "published",
    version: 1,
  };
}

function fact(factId, section, conceptId, label, value, synonyms) {
  return {
    factId,
    section,
    conceptId,
    label,
    value,
    naturalResponse: value,
    revealPolicy: "IF_RELEVANT_QUESTION",
    triggerConcepts: [conceptId],
    synonyms,
    relatedChecklistItemIds: [],
  };
}

function checklist({ title, slug, items }) {
  return {
    title,
    slug,
    sourceScoring: { maxRawScore: 8, description: "8 one-mark checklist rows" },
    weightConfiguration: { critical: 3, major: 2, minor: 1 },
    sections: [{ sectionId: "station_checklist", title: "Marking Checklist", items }],
    version: 1,
    status: "published",
  };
}

function row(itemId, label, description, expectedConcepts, relatedFactIds, weightCategory) {
  return {
    itemId,
    label,
    description,
    category: "history",
    expectedConcepts,
    relatedFactIds,
    weightCategory,
    maxRawScore: 1,
    allowPartial: true,
    criticalSafetyItem: weightCategory === "critical",
    commonMistake: "",
    remediationText: description,
    order: 1,
  };
}
